places = ['Tokyo', 'Paris', 'Los Angeles', 'Toronoto', 'New York']
print("Original list:")
print(places)
print("\nAlphabetical order (sorted()):")
print(sorted(places))
print("\nOriginal list still intact:")
print(places)
print("\nReverse alphabetical order (sorted()):")
print(sorted(places, reverse=True))
print("\nOriginal list still intact:")
print(places)
print("\nUsing reverse() to change order:")
places.reverse()
print(places)
print("\nUsing reverse() again to restore:")
places.reverse()
print(places)
print("\nUsing sort() for alphabetical order:")
places.sort()
print(places)
print("\nUsing sort() for reverse alphabetical order:")
places.sort(reverse=True)
print(places)